const getFavs=()=>JSON.parse(localStorage.getItem('baseraFavs')||'[]');
const setFavs=x=>localStorage.setItem('baseraFavs',JSON.stringify(x));
const getCompare=()=>JSON.parse(localStorage.getItem('baseraCompare')||'[]');
const setCompare=x=>localStorage.setItem('baseraCompare',JSON.stringify(x));
function updateCounts(){document.querySelectorAll('#favCount').forEach(e=>e.textContent=getFavs().length);}
function money(n){return '₹'+Number(n).toLocaleString('en-IN');}
function card(p){
 const fav=getFavs().includes(p.id), cmp=getCompare().includes(p.id);
 return `<article class="listing-card">
   <div class="card-img ${p.type.toLowerCase()}"><span>${p.image}</span><button class="heart ${fav?'liked':''}" onclick="toggleFav(${p.id})">${fav?'♥':'♡'}</button>${p.verified?'<em>✓ Verified</em>':''}</div>
   <div class="card-body"><div class="type-row"><span>${p.type}</span><span>📍 ${p.distance} km</span></div>
   <h3>${p.name}</h3><p class="muted">${p.location}</p>
   <div class="rating">★ ${p.rating} <small>(${p.reviews} reviews)</small></div>
   <div class="amenities">${p.amenities.slice(0,3).map(a=>`<span>${a}</span>`).join('')}${p.amenities.length>3?`<span>+${p.amenities.length-3}</span>`:''}</div>
   <div class="price-row"><div><strong>${money(p.price)}</strong><small>/month</small></div><button class="outline small ${cmp?'selected':''}" onclick="toggleCompare(${p.id})">${cmp?'✓ Added':'Compare'}</button><a class="primary small" href="property.html?id=${p.id}">View</a></div>
   </div></article>`;
}
function toggleFav(id){let a=getFavs();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];setFavs(a);updateCounts();renderAll();}
function toggleCompare(id){let a=getCompare();if(a.includes(id))a=a.filter(x=>x!==id);else if(a.length<4)a.push(id);else return alert('You can compare up to 4 properties.');setCompare(a);renderAll();}
function renderAll(){if(document.getElementById('homeListings'))document.getElementById('homeListings').innerHTML=properties.slice(0,4).map(card).join(''); if(document.getElementById('listingGrid'))renderSearch();if(document.getElementById('favArea'))renderFavs();if(document.getElementById('compareArea'))renderCompare();if(document.getElementById('propertyDetail'))renderProperty();updateCounts();}
function renderSearch(){
 const q=(document.getElementById('q').value||'').toLowerCase(), type=document.getElementById('type').value, max=+document.getElementById('rent').value, room=document.getElementById('room').value, min=+document.getElementById('rating').value, food=document.getElementById('food').checked,wifi=document.getElementById('wifi').checked,ac=document.getElementById('ac').checked,ver=document.getElementById('verified').checked;
 let list=properties.filter(p=>(!q||`${p.name} ${p.area} ${p.location} ${p.type}`.toLowerCase().includes(q))&&(!type||p.type===type)&&p.price<=max&&(!room||p.room===room)&&p.rating>=min&&(!food||p.food)&&(!wifi||p.wifi)&&(!ac||p.ac)&&(!ver||p.verified));
 const sort=document.getElementById('sort').value;if(sort==='priceLow')list.sort((a,b)=>a.price-b.price);if(sort==='priceHigh')list.sort((a,b)=>b.price-a.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);
 document.getElementById('resultCount').textContent=list.length;document.getElementById('listingGrid').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><span>⌕</span><h3>No stays found</h3><p>Try changing your filters or search area.</p></div>`;
}
function resetFilters(){document.getElementById('q').value='';document.getElementById('type').value='';document.getElementById('rent').value=15000;document.getElementById('room').value='';document.getElementById('rating').value=0;['food','wifi','ac','verified'].forEach(x=>document.getElementById(x).checked=false);document.getElementById('rentValue').textContent='₹15,000';renderSearch();}
function renderFavs(){const a=getFavs().map(id=>properties.find(p=>p.id===id)).filter(Boolean);document.getElementById('favArea').innerHTML=a.length?a.map(card).join(''):`<div class="empty"><span>♡</span><h3>No favourites yet</h3><p>Save properties you like and they'll appear here.</p><a class="primary" href="search.html">Explore stays →</a></div>`;}
function renderCompare(){const a=getCompare().map(id=>properties.find(p=>p.id===id)).filter(Boolean);if(!a.length){document.getElementById('compareArea').innerHTML=`<div class="empty"><span>⇄</span><h3>Nothing to compare yet</h3><p>Go to Find a Stay and add up to four properties.</p><a class="primary" href="search.html">Find stays →</a></div>`;return;}document.getElementById('compareArea').innerHTML=`<div class="compare-table"><table><thead><tr><th>Feature</th>${a.map(p=>`<th><div class="compare-img">${p.image}</div><strong>${p.name}</strong><button onclick="toggleCompare(${p.id})">Remove</button></th>`).join('')}</tr></thead><tbody>${[['Type',p=>p.type],['Monthly rent',p=>money(p.price)],['Deposit',p=>money(p.deposit)],['Distance',p=>p.distance+' km'],['Room',p=>p.room],['Rating',p=>'★ '+p.rating+' / 5'],['Food',p=>p.food?'✓ Yes':'—'],['Wi-Fi',p=>p.wifi?'✓ Yes':'—'],['AC',p=>p.ac?'✓ Yes':'—'],['Laundry',p=>p.laundry?'✓ Yes':'—'],['Verified',p=>p.verified?'✓ Verified':'Not verified']].map(([k,fn])=>`<tr><td>${k}</td>${a.map(p=>`<td>${fn(p)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function renderProperty(){const id=+new URLSearchParams(location.search).get('id')||1,p=properties.find(x=>x.id===id)||properties[0],fav=getFavs().includes(p.id);document.title=p.name+' | Basera';document.getElementById('propertyDetail').innerHTML=`<div class="breadcrumb"><a href="search.html">Find a Stay</a> / ${p.name}</div><section class="detail-hero"><div class="detail-image ${p.type.toLowerCase()}">${p.image}</div><div><div class="type-row"><span>${p.type}</span>${p.verified?'<span class="verified">✓ Verified property</span>':''}</div><h1>${p.name}</h1><p class="location">📍 ${p.location} · ${p.distance} km from college</p><div class="rating big">★ ${p.rating} <small>${p.reviews} student reviews</small></div><div class="detail-price"><strong>${money(p.price)}</strong> <span>/ month</span><small>Deposit: ${money(p.deposit)}</small></div><div class="detail-actions"><button class="primary" onclick="enquire('${p.name}')">Enquire Now →</button><button class="outline" onclick="toggleFav(${p.id})">${fav?'♥ Saved':'♡ Save'}</button><button class="outline" onclick="toggleCompare(${p.id})">⇄ Compare</button></div></div></section><section class="detail-grid"><div class="detail-main"><h2>About this stay</h2><p>${p.desc}</p><h2>Amenities</h2><div class="amenity-grid">${p.amenities.map(a=>`<div>✓ ${a}</div>`).join('')}</div><h2>What students say</h2><div class="review"><strong>★★★★★</strong><p>“Good location and the facilities are as described. The search and comparison on Basera made shortlisting easier.”</p><small>— Student review · prototype data</small></div></div><aside class="cost-card"><h3>Estimated monthly cost</h3><div><span>Rent</span><strong>${money(p.price)}</strong></div><div><span>Food & utilities</span><strong>${money(Math.round(p.price*.15))}</strong></div><div class="total"><span>Estimated total</span><strong>${money(Math.round(p.price*1.15))}</strong></div><p>Estimate for prototype demonstration. Actual costs may vary.</p></aside></section>`;}
function enquire(name){alert(`Enquiry recorded for ${name}!\n\nIn the MERN version, this action will create an enquiry in the database and notify the property owner.`);}
function goSearch(){const q=document.getElementById('homeSearch').value,type=document.getElementById('homeType').value;location.href=`search.html?q=${encodeURIComponent(q)}&type=${encodeURIComponent(type)}`;}
function quickSearch(q){location.href=`search.html?q=${encodeURIComponent(q)}`;}
document.addEventListener('DOMContentLoaded',()=>{updateCounts();if(document.getElementById('listingGrid')){const u=new URLSearchParams(location.search);document.getElementById('q').value=u.get('q')||'';document.getElementById('type').value=u.get('type')||'';document.getElementById('rent').addEventListener('input',e=>{document.getElementById('rentValue').textContent=money(e.target.value);renderSearch()});['q','type','room','rating','food','wifi','ac','verified','sort'].forEach(id=>document.getElementById(id).addEventListener(id==='q'?'input':'change',renderSearch));renderSearch();}renderAll();if(document.getElementById('ownerForm'))document.getElementById('ownerForm').addEventListener('submit',e=>{e.preventDefault();document.getElementById('ownerSuccess').classList.remove('hidden');e.target.reset();});});
