const properties = [
{id:1,name:"The Student Nest",type:"PG",area:"Muradnagar",location:"Near KIET, Muradnagar",price:7500,deposit:7500,room:"Single",distance:1.2,rating:4.7,reviews:84,verified:true,food:true,wifi:true,ac:true,laundry:true,parking:true,image:"🏠",desc:"Bright, student-friendly PG with food, Wi-Fi and housekeeping near KIET.",amenities:["Wi-Fi","Food","AC","Laundry","Housekeeping","Power Backup"]},
{id:2,name:"Campus View Residency",type:"PG",area:"Muradnagar",location:"Delhi-Meerut Road, Muradnagar",price:6500,deposit:6500,room:"Double",distance:1.8,rating:4.4,reviews:51,verified:true,food:true,wifi:true,ac:false,laundry:true,parking:true,image:"🏢",desc:"Affordable shared accommodation with easy access to college and local markets.",amenities:["Wi-Fi","Food","Laundry","Parking","Power Backup"]},
{id:3,name:"UrbanNest 2BHK",type:"Flat",area:"Raj Nagar",location:"Raj Nagar Extension",price:11500,deposit:23000,room:"2 BHK",distance:8.4,rating:4.6,reviews:39,verified:true,food:false,wifi:true,ac:true,laundry:false,parking:true,image:"🏙️",desc:"Fully furnished 2BHK ideal for students sharing with friends.",amenities:["Wi-Fi","AC","Furnished","Parking","Gated Society"]},
{id:4,name:"Scholar's Haven",type:"Hostel",area:"Vaishali",location:"Sector 4, Vaishali",price:5800,deposit:5800,room:"Triple",distance:16.2,rating:4.2,reviews:27,verified:false,food:true,wifi:true,ac:false,laundry:true,parking:false,image:"🏫",desc:"Budget hostel with meals and laundry facilities.",amenities:["Wi-Fi","Food","Laundry","Study Area"]},
{id:5,name:"Maple Girls PG",type:"PG",area:"Crossings Republik",location:"Crossings Republik",price:8500,deposit:8500,room:"Single",distance:12.5,rating:4.8,reviews:112,verified:true,food:true,wifi:true,ac:true,laundry:true,parking:true,image:"🌿",desc:"Comfortable girls PG with modern rooms, meals and secure entry.",amenities:["Wi-Fi","Food","AC","Laundry","CCTV","Parking"]},
{id:6,name:"Metro Homes",type:"Flat",area:"Indirapuram",location:"Ahinsa Khand, Indirapuram",price:9000,deposit:18000,room:"1 BHK",distance:14.7,rating:4.5,reviews:45,verified:false,food:false,wifi:true,ac:true,laundry:false,parking:true,image:"🏡",desc:"Compact furnished 1BHK for students or young professionals.",amenities:["Wi-Fi","AC","Furnished","Parking"]},
{id:7,name:"Green View PG",type:"PG",area:"Muradnagar",location:"Main Market, Muradnagar",price:7200,deposit:7200,room:"Double",distance:2.4,rating:4.1,reviews:19,verified:true,food:false,wifi:true,ac:true,laundry:true,parking:false,image:"🌱",desc:"Clean shared rooms with flexible meal options and nearby daily essentials.",amenities:["Wi-Fi","AC","Laundry","Housekeeping"]},
{id:8,name:"StudySquare Hostel",type:"Hostel",area:"Modinagar",location:"Modinagar",price:5000,deposit:5000,room:"Triple",distance:9.1,rating:4.3,reviews:34,verified:true,food:true,wifi:true,ac:false,laundry:true,parking:true,image:"📚",desc:"Student hostel with study spaces, meals and easy local transport.",amenities:["Wi-Fi","Food","Laundry","Study Area","Parking"]}
];